### ISSUE TITLE
Unable to find package lua-resty-url

### ISSUE THREAD

**Issue by siozosdr** [3scale/lua-resty-url#10]
Hello I tried installing your repo with opm but I get the folloing error:

```
$ opm get 3scale/lua-resty-url
* Fetching 3scale/lua-resty-url  
ERROR: failed to find package 3scale/lua-resty-url: package lua-resty-url not found under account 3scale.
```

Any suggestions?

**Comment by davidor** [comment]
It's on Luarocks https://luarocks.org/modules/3scale/lua-resty-url , but it has not been published on `opm`.
@mikz Should we upload this library to `opm` too?

**Comment by mikz** [comment]
The file is there: https://github.com/3scale/lua-resty-url/blob/4710562caaeb71d86a00b9c14ab546bc1b6ce0f3/dist.ini
I just never got to publish it I guess. Will try.

**Comment by siozosdr** [comment]
Hi guys, thank you for your quick reply! So is there something I need to do from my side?

**Comment by mikz** [comment]
@siozosdr no need. Thanks for reporting. 0.3.3 is now on http://opm.openresty.org.
Feel free to reopen if it does not work for you.
