### ISSUE TITLE
"nesting of [[...]] is deprecated"

### ISSUE THREAD

**Issue by chris-jansson** [3scale/lua-resty-url#11]
I'm running Lua 5.1.5 on a Macbook Pro. When I try to load this library like the README specifies:

    local resty_url = require 'resty.url'

I get the following error from the LuaRocks loader:

```
Error → /usr/local/share/lua/5.1/luarocks/loader.lua @ 147
suite spec/foo_spec.lua
/usr/local/share/lua/5.1/luarocks/loader.lua:147: error loading module 'resty.url' from file '/usr/local/share/lua/5.1/resty/url.lua':
	/usr/local/share/lua/5.1/resty/url.lua:64: nesting of [[...]] is deprecated near '['
```

Any plans to update the deprecated code? Thanks

**Comment by mikz** [comment]
Interesting. We are only running on LuaJIT 2.1 that is based on Lua 5.1 and it works there just fine.

@chris-jansson could you try https://github.com/3scale/lua-resty-url/pull/12 and see if it works?

**Comment by chris-jansson** [comment]
Thanks for the quick reply! I'm away from that computer until Monday, but will check then and report back.

**Comment by chris-jansson** [comment]
That fixed it. Thanks!
