### ISSUE TITLE
parse url without username

### ISSUE THREAD

**Issue by virusdefender** [3scale/lua-resty-url#9]
```lua
local url = require("url")
local conn = url.parse("redis://:foobar@mgt-redis-addr")
ngx.say(conn.password)
```

will get `nil`

**Comment by mikz** [comment]
Curl does not handle this case either: 

```shell
curl -v http://:password@echo-api.3scale.net/test
```

But I'll see what I can do as it makes sense in the redis use case where there is just a password.

**Comment by mikz** [comment]
@virusdefender thanks for reporting! Pushed 0.3.3 with the fix to both luarocks and opm.
